result_root: fix undefined method `goto_commit' for nil:NilClass`
This patch is used to fix below error:

NoMethodError: undefined method `goto_commit' for nil:NilClass
from /lkp/yexl/src/lib/bisect-result.rb:350:in `block in parent_mresult_roots'

This issue is due to mresult_root return nil in bisect-result.rb.

Root cause is that job file is not so reliable due to legacy issue, eg.

$ less /result/pft/defaults/vm-lkp-wsx03-1G/debian-x86_64-2015-02-07.cgz/x86_64-rhel/gcc-6/4eedfe79dcaeaab362194de9bf4730ba87c99834/job.yaml | grep rootfs

rootfs: debian-x86_64.cgz

Actually exact rootfs used is debian-x86_64-2015-02-07.cgz, so MResultRoot.goto_commit maybe mislead by
it to generated non-exist result root path for other commit, thus return nil for mresult_root.
Use path info directly instead since it's more accurate.

Signed-off-by: Xiaolong Ye <xiaolong.ye@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>